[package]
name = "namsicd-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13"
tonic = "0.13"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
tonic-build = "0.13"
