name: Continuous integration test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cargo fmt --verbose --check
    - run: cargo clippy
    - run: cargo build --verbose
    - run: cargo test --verbose

